# Generated by Django 5.0.7 on 2024-09-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_links', models.URLField()),
                ('project_description', models.TextField(max_length=500)),
                ('project_stack', models.TextField(max_length=500)),
                ('duration', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=200)),
                ('Proficiency_level', models.CharField(max_length=40)),
                ('category', models.CharField(max_length=50)),
                ('years_of_experience', models.DecimalField(decimal_places=1, max_digits=2)),
                ('icon', models.URLField()),
                ('last_used', models.CharField(max_length=10)),
                ('description', models.TextField(max_length=1000)),
                ('skill_type', models.CharField(max_length=50)),
                ('related_projects', models.ManyToManyField(to='user.projects')),
            ],
        ),
    ]
