# Generated by Django 5.0.7 on 2024-09-24 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_related_projects_skills_projects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='projects',
            new_name='project_name',
        ),
    ]
