# Generated by Django 5.0.7 on 2024-09-25 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_experience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='description',
            new_name='responsibilities',
        ),
    ]
