# Generated by Django 5.0.7 on 2024-09-25 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_rename_project_links_projects_project_link'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='projects',
            new_name='Project',
        ),
        migrations.RenameModel(
            old_name='skills',
            new_name='Skill',
        ),
    ]
