# Generated by Django 5.0.7 on 2024-09-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_rename_projects_project_rename_skills_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('profile_pic', models.ImageField(upload_to='images')),
                ('bio', models.TextField(max_length=500)),
                ('location', models.CharField(max_length=100)),
                ('linkdin', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
