# Generated by Django 5.0.7 on 2024-09-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_education'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='Proficiency_level',
            new_name='proficiency_level',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='project_name',
        ),
        migrations.AddField(
            model_name='skill',
            name='project',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('technical', 'Technical Skill'), ('other', 'Other Skill')], default='technical', max_length=50),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_type',
            field=models.CharField(choices=[('frontend', 'Frontend Development'), ('backend', 'Backend Development'), ('database', 'Database Management'), ('management', 'Project Management')], default='frontend', max_length=50),
        ),
    ]
